<?php
/** 
* Depreciated by file.php as it takes live data from ICANN.
**/
$tld = array(
		array("ac","Ascension Island"),
		array("ad","Andorra"),
		array("ae","United Arab Emirates"),
		array("af","Afghanistan"),
		array("ag","Antigua and Barbuda; Also used as acronym for 'Aktien Gesellschaft', stands for public stock corporation) in Germany, Switserland and Austria"),
		array("ai","Anguilla"),
		array("al","Albania"),
		array("am","Armenia; Also used in AM Radio Station Industry"),
		array("an","Netherlands Antilles"),
		array("ao","Angola"),
		array("ar","Argentina"),
		array("as","American Samoa"),
		array("at","Austria"),
		array("au","Australia"),
		array("aw","Aruba"),
		array("az","Azerbaijan"),
		array("ba","Bosnia and Herzegovina"),
		array("bb","Barbados"),
		array("bd","Bangladesh"),
		array("be","Belgium"),
		array("bf","Burkina Faso"),
		array("bg","Bulgaria"),
		array("bh","Bahrain"),
		array("bi","Burundi"),
		array("bj","Benin"),
		array("bm","Bermuda"),
		array("bn","Brunei Darussalam"),
		array("bo","Bolivia"),
		array("br","Brazil"),
		array("bs","Bahamas"),
		array("bt","Bhutan"),
		array("bw","Botswana"),
		array("by","Belarus"),
		array("bz","Belize"),
		array("ca","Canada"),
		array("cc","Cocos (Keeling) Islands; Also used for various acronyms"),
		array("cd","Democratic Republic of the Congo"),
		array("cg","Republic of Congo"),
		array("ch","Switzerland"),
		array("ci","Ivory Coast"),
		array("ck","Cook Island"),
		array("cl","Chile"),
		array("cm","Cameroon"),
		array("cn","China"),
		array("co","Colombia"),
		array("cr","Costa Rica"),
		array("cu","Cuba"),
		array("cv","Cape Verde"),
		array("cx","Christmas Island"),
		array("cy","Cyprus"),
		array("cz","Czech Republic"),
		array("de","Germany"),
		array("dj","Djibouti"),
		array("dk","Denmark"),
		array("dm","Dominica"),
		array("do","Dominican Republic"),
		array("dz","Algeria"),
		array("ec","Ecuador"),
		array("ee","Estonia"),
		array("eg","Egypt"),
		array("es","Spain"),
		array("et","Ethiopia"),
		array("eu","European Union"),
		array("fi","Finland"),
		array("fj","Fiji"),
		array("fk","Falkland Islands"),
		array("fm","Federal States of Micronesia; Also used in the FM Radio Station Industry."),
		array("fo","Faroe Islands"),
		array("fr","France"),
		array("ge","Georgia"),
		array("gf","French Guiana"),
		array("gg","Guernsey"),
		array("gh","Ghana"),
		array("gi","Gibraltar"),
		array("gl","Greenland"),
		array("gm","Gambia"),
		array("gn","Guinea"),
		array("gp","Guadeloupe"),
		array("gq","Equatorial Guinea"),
		array("gr","Greece"),
		array("gs","South Georgia and the South Sandwich islands"),
		array("gt","Guatemala"),
		array("gu","Guam"),
		array("hk","Hong Kong"),
		array("hm","Heard and McDonalds Islands"),
		array("hn","Honduras"),
		array("hr","Croatia"),
		array("ht","Haiti"),
		array("hu","Hungary"),
		array("id","Indonesia"),
		array("ie","Ireland"),
		array("il","Israel"),
		array("im","Isle of Man"),
		array("in","India; Also used like 'www.restaurants.in/washington'"),
		array("io","The British Indian Ocean Territory; Also used for various acronyms"),
		array("ir","Iran"),
		array("is","Iceland"),
		array("it","Italy and the Information technology business sector"),
		array("je","Jersey"),
		array("jm","Jamaica"),
		array("jo","Jordan"),
		array("jp","Japan"),
		array("ke","Kenya"),
		array("kg","Kyrgyzstan"),
		array("kh","Cambodia"),
		array("ki","Kiribati"),
		array("kr","Republic of Korea"),
		array("kw","Kuwait"),
		array("ky","Cayman Islands"),
		array("kz","Kazakhstan"),
		array("la","Lao People's Democratic Republic, Los Angeles, the State Code of Louisiana in the U.S.."),
		array("lb","Lebanon"),
		array("lc","Saint Lucia"),
		array("li","Liechtenstein"),
		array("lk","Sri Lanka"),
		array("lr","Liberia"),
		array("ls","Lesotho"),
		array("lt","Lethuania"),
		array("lu","Luxembourg"),
		array("lv","Latvia"),
		array("ly","Libyan Arab Jamahiriya"),
		array("ma","Marocco"),
		array("mc","Monaco"),
		array("md","Repbulic of Moldova, medical industry"),
		array("mg","Madagascar"),
		array("mh","Marshall Islands"),
		array("mk","Macedonia"),
		array("ml","Mali"),
		array("mm","Myanmar"),
		array("mn","Mongolia"),
		array("mo","Macau"),
		array("mp","Northern Mariana Islands"),
		array("mq","Martinique"),
		array("mr","Mauritania"),
		array("ms","Montserrat"),
		array("mt","Malta"),
		array("mu","Mauritius"),
		array("mv","Maldives"),
		array("mw","Malawi"),
		array("mx","Mexico"),
		array("my","Malaysia"),
		array("mz","Mozambique"),
		array("na","Namibia"),
		array("nc","New Caledonia"),
		array("ne","Niger"),
		array("nf","Norfolk Island"),
		array("ng","Nigeria"),
		array("ni","Nicaragua"),
		array("nl","Netherlands"),
		array("no","Norway"),
		array("np","Nepal"),
		array("nr","Nauru"),
		array("nu","Niue"),
		array("nz","New Zealand"),
		array("om","Oman"),
		array("pa","Panama"),
		array("pe","Peru"),
		array("pf","French Polynesia"),
		array("pg","Papua New Guinea"),
		array("ph","Philippines"),
		array("pk","Pakistan"),
		array("pl","Poland"),
		array("pm","Saint Pierre and Miqeulon"),
		array("pn","Pitcairn Island"),
		array("pr","Puerto Rico"),
		array("ps","Palestinian Territories"),
		array("pt","Portugal"),
		array("pw","Palau"),
		array("py","Paraguay"),
		array("qa","Qatar"),
		array("re","Reunion Island"),
		array("ro","Romania"),
		array("ru","Russian Federation"),
		array("rw","Rwanda"),
		array("sa","Saudi Arabia"),
		array("sb","Solomon Islands"),
		array("sc","Seychelles; Also used for various acronyms"),
		array("sd","Sudan"),
		array("se","Sweden"),
		array("sg","Singapore"),
		array("sh","Saint Helena"),
		array("si","Slovenia"),
		array("sk","Slovak Republic"),
		array("sl","Sierra Leone"),
		array("sm","San Marino"),
		array("sn","Senegal"),
		array("so","Somalia"),
		array("sr","Suriname"),
		array("st","Sao Tome and Principe"),
		array("su","Former Soviet Union"),
		array("sv","El Salvador"),
		array("sy","Syrian Arab Republic"),
		array("sz","Swaziland"),
		array("tc","Turks and Caicos islands"),
		array("td","Chad"),
		array("tf","French Southern Territories"),
		array("tg","Togo"),
		array("th","Thailand"),
		array("tj","Tajikistan"),
		array("tk","Tokelau, Telecommunication in Germany"),
		array("tm","Turkmenistan"),
		array("tn","Tunesia"),
		array("to","Tonga"),
		array("tp","East Timor (changed to tl extension)"),
		array("tr","Turkey"),
		array("tt","Trinidad and Tobago"),
		array("tv","Tuvalu, Television industry"),
		array("tw","Taiwan"),
		array("tz","Tanzania"),
		array("ua","Ukraine"),
		array("ug","Uganda"),
		array("uk","United Kingdom"),
		array("um","United States Minor Outlaying Islands"),
		array("us","United States"),
		array("uy","Uruguay"),
		array("uz","Uzbekistan"),
		array("vc","Saint Vincent and the Grenadines"),
		array("ve","Venezuela"),
		array("vg","British Virgin Islands"),
		array("vi","US Virgin Islands"),
		array("vn","Vietnam"),
		array("vu","Vanuatu"),
		array("wf","Wallis and Futuna Islands"),
		array("ws","Western Samoa, alternative to a .com, .net or a .org"),
		array("ye","Yemen"),
		array("yt","Mayotte"),
		array("yu","Yugoslavia (Serbia and Montenegro)"),
		array("za","South Africa"),
		array("zm","Zambia"),
		array("zw","Zimbabwe")
	);

function searchForId($id, $array) {
   foreach ($array as $key => $val) {
       if ($val[0] === $id) {
           return $key;
       }
   }
   return null;
}
?>